#!/usr/bin/env python3
import hdfexplorer.tree_browser
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

win = hdfexplorer.tree_browser.BrowserWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
